$accent = rgba(9fefffff) 
$primary = rgba(9fefffff)
$secondary = rgba(cde7edff)
$success = rgba(dbe1ffff)
$background = rgba(0e1416ff)
$surface = rgba(0e1416ff)
$surface-variant = rgba(3f484aff)
$on-primary = rgba(00363eff)
$on-secondary = rgba(1c3439ff)
$on-surface = rgba(dee3e5ff)
$on-surface-variant = rgba(bfc8caff)
$outline = rgba(899295ff)
$outline-variant = rgba(3f484aff)