$accent = rgba(ffd6faff) 
$primary = rgba(ffd6faff)
$secondary = rgba(f5dbf0ff)
$success = rgba(ffdad3ff)
$background = rgba(171216ff)
$surface = rgba(171216ff)
$surface-variant = rgba(4d444bff)
$on-primary = rgba(4a204cff)
$on-secondary = rgba(3c2b3bff)
$on-surface = rgba(ebdfe6ff)
$on-surface-variant = rgba(d0c3ccff)
$outline = rgba(998d96ff)
$outline-variant = rgba(4d444bff)