exec-once = waybar & swww-daemon & dunst & hypridle
exec-once = sleep 0.6 && ~/.config/hypr/scripts/wallpaper.sh
exec-once = hyprctl dispatch workspace 3 # open workspace 3 on boot
exec-once = ibus start

source=hyprland/rules.conf
source=hyprland/others.conf
source=hyprland/keybinds.conf
source=hyprland/animations.conf
source=hyprland/apperance.conf
