$launcher = ~/.config/rofi/scripts/launcher.sh
$motrix = $HOME/Desktop/motrix/motrix
$full_screen = ~/.config/hypr/scripts/screenshot.sh full
$region_screenshot = ~/.config/hypr/scripts/screenshot.sh region
$window_only = ~/.config/hypr/scripts/screenshot.sh window
