exec-once = waybar & swww-daemon & dunst & hypridle
exec-once = sleep 0.6 && ~/.config/hypr/scripts/wallpaper.sh
exec-once = hyprctl dispatch workspace 3 # open workspace 3 on boot
exec-once = ibus start
exec-once = wl-paste --type text --watch cliphist store
# exec-once = sleep 5 && [ "$(nmcli -t -f WIFI g)" = "enabled" ] && notify-send -i network-wireless "WiFi Connected" "$(nmcli -t -f NAME connection show --active | head -n1)"
