# WINDOW RULES
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# TRANSPARENCY
windowrulev2 = opacity 0.75, class:.*, floating:1 # For floating windows

# KITTY
windowrulev2 = opacity 0.75, class:kitty  # Custom opacity for kitty
windowrulev2 = opacity 1, class:feh  # Custom opacity for kitty
windowrulev2 = float, class:^(kitty)$
windowrulev2 = opacity 0.60, class:^(kitty)$, floating:1 # For floating windows

# FLOATING APPS
# windowrulev2 = float, class:^(ibus-ui-gtk3)$
# windowrule = float, class:^(org.gnome.Nautilus)$ 
# windowrule = float, class:^(nm-connection-editor)$
# windowrule = float, class:^(nwg-look)$
# windowrule = float, class:^(blueman-manager)$
# windowrule = float, class:^(Motrix)$
# windowrule = float, class:^(font-manager)$
# windowrule = float, class:^(com.github.FontManager.FontViewer)$
# windowrule = float, class:^(feh)$
# windowrule = float, title:^(Open File|Open Folder|Save As|Select|Choose)$

# FLOATING WINDOW SIZE
windowrulev2 = float, size 800 500, class:^(kitty)$
windowrulev2 = float, size 800 500, class:^(Motrix)$
windowrulev2 = float, size 1000 600, class:^(feh)$
windowrulev2 = float, size 800 500, class:^(org.gnome.Nautilus)$
windowrulev2 = float, size 800 500, class:^(nm-connection-editor)$
windowrulev2 = float, size 200 100, class:^(ibus-ui-gtk3)$
windowrulev2 = float, size 800 500, class:^(nwg-look)$
windowrulev2 = float, size 800 500, class:^(font-manager)$
windowrulev2 = float, size 800 500, title:^(Open File|Open Folder|Save As|Select|Choose)$
windowrulev2 = float, size 800 500, class:^(kitty)$

# EMOJI PICKER
windowrulev2 = float, title:^(HyprEmoji)$ 

